import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

module.exports = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },

  subContainer: {
    marginTop: Platform.OS === "ios" ? 5 : 10,
    backgroundColor: "#ffff",
  },
  iconi: {
    backgroundColor: "whitesmoke",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
    height: 35,
    width: 35,
    position: "absolute",
    top: Platform.OS === "ios" ? 8 : 38,
    left: Platform.OS === "ios" ? 15 : 10,
  },
  form: {
    flex: 1,
    justifyContent: "space-between",
  },
  topview: {
    backgroundColor: "#d6d6d2",
    height: "96%",
    width: "63%",
    //borderColor: "#d6d6d2",
  },
  image: {
    borderColor: "gray",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    position: "absolute",
    height: 35,
    borderRadius: 2,
  },
  umg: {
    borderWidth: 1,
    borderColor: "gray",
    alignItems: "center",
    justifyContent: "center",
    width: 105,
    position: "absolute",
    top: "5%",
    right: Platform.OS === "android" ? -35 : -28,
    height: 105,
    borderRadius: 2,
  },
  img: {
    height: 350,
    width: 450,
    alignSelf: "center",
    margin: 8,
  },
  vimg: {
    height: 120,
    width: "60%",
    alignSelf: "center",
  },
  btn: {
    height: 48,
    width: "49%",
    alignSelf: "center",
    backgroundColor: "#66276D",
    borderTopRightRadius: 95,
    borderBottomRightRadius: 6,
  },
  btnsm: {
    height: 50,
    width: "60%",
    borderRadius: 5,
    backgroundColor: "#66276D",
    justifyContent: "center",
    alignSelf: "center",
    margin: 8,
  },
  btnsmm: {
    height: 80,
    width: "28%",
    borderRadius: 5,
    backgroundColor: "#FCDEBD",
    justifyContent: "center",
    alignSelf: "center",
    margin: 8,
    flexDirection: "column",
  },
  imgbtn: {
    height: 45,
    width: "95%",
    // alignSelf: "center",
    backgroundColor: "#66276D",
    borderRadius: 2,
    marginLeft: 15,
    top: 95,
  },
  imbtn: {
    height: 34,
    width: "30%",
    // alignSelf: "center",
    backgroundColor: "#66276D",
    borderRadius: 2,
  },
  btnsTxt: {
    fontSize: 18,
    fontWeight: "normal",
    justifyContent: "center",
    color: "white",
    padding: 10,
    alignSelf: "center",
  },
  btnsxt: {
    fontSize: 12,
    fontWeight: "normal",
    justifyContent: "center",
    color: "white",
    padding: 10,
    alignSelf: "center",
  },
  btnTxt: {
    fontSize: 18,
    fontWeight: "normal",
    justifyContent: "center",
    color: "white",
    padding: 10,
    alignSelf: "center",
  },
  txt: {
    fontSize: 16,
    fontWeight: "bold",
    justifyContent: "center",
    color: "black",
    padding: 15,
    //fontFamily: "",
  },
  txtsm: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    alignSelf: "center",
  },
  txtsmm: {
    fontSize: 20,
    fontWeight: "bold",
    color: "black",
    alignSelf: "center",
  },

  text: {
    fontSize: 14,
    fontWeight: "normal",
    justifyContent: "center",
    color: "normal",
    padding: 15,
    //fontFamily: "",
  },
  txtx: {
    fontSize: 13,
    fontWeight: "bold",
    justifyContent: "center",
    color: "black",
    padding: 15,
    //fontFamily: "",
  },
  onbtxt: {
    fontSize: 18,
    fontWeight: "bold",
    justifyContent: "center",
    color: "black",
    alignSelf: "center",
    //padding: 15,
    //fontFamily: "",
  },
  ontxt: {
    fontSize: 19,
    fontWeight: "normal",
    justifyContent: "center",
    color: "black",
    alignSelf: "center",
    //padding: 15,
    //fontFamily: "",
  },
  inputkb: {
    alignSelf: "center",
  },
  checkbox: {
    //margin: 1,
    position: "absolute",
    top: "25%",
    left: -5,
  },
  root: { margin: 45 },
  title: { textAlign: "center", fontSize: 20 },
  codeFieldRoot: { marginTop: 50 },
  cell: {
    margin: 2,
    width: 40,
    height: 40,
    //lineHeight: 38,
    fontSize: 34,
    borderWidth: 1,
    borderColor: "black",
    textAlign: "center",
  },
  focusCell: {
    borderColor: "black",
  },
  pickedDateContainer: {
    padding: 20,
    //backgroundColor: "blue",
    borderRadius: 10,
  },
  pickedDate: {
    fontSize: 18,
    color: "black",
  },
  btnContainer: {
    padding: 30,
  },
  // This only works on iOS
  datePicker: {
    width: 320,
    height: 260,
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
  },
  uimg: {
    borderWidth: 1,

    //borderColor: "#",
    //backgroundColor: "grey",
    alignItems: "center",
    // justifyContent: "center",
    //margin: Platform.OS === "android" ? 5 : 5,
    width: 90,
    position: "absolute",
    top: "45%",
    alignSelf: "center",
    height: 90,
    borderRadius: 80,
  },
  kuimg: {
    //borderWidth: 1,
    //borderColor: "#",
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    width: 100,
    position: "absolute",
    //top: "45%",
    alignSelf: "center",
    height: 100,
    borderRadius: 100,
  },
  // pin styling
  avoidingView: {
    borderRadius: 10,
    height: 150,
    width: 30,
  },
  containerCodePin: {
    borderRadius: 10,
  },
  codePin: {
    borderRadius: 25,
    backgroundColor: "#FCDEBD",
    //alignSelf: "center",
  },
  pinStyle: {
    marginLeft: Platform.OS === "ios" ? 35 : 29,
    marginRight: Platform.OS === "ios" ? -12 : -8,
    height: Platform.OS === "android" ? 60 : 50,
    alignItems: "center",
    // width: 25,
  },
  reset: {
    backgroundColor: "#FCDEBD",
    marginTop: Platform.OS === "ios" ? 350 : 400,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    height: 700,
    width: "100%",
    //flex: 1,
  },
  dropdown: {
    height: 30,
    backgroundColor: "transparent",
    borderBottomColor: "gray",
    borderBottomWidth: 1,
    margin: 16,
    // margin: 16,
    // height: 50,
    // backgroundColor: "white",
    // borderRadius: 12,
    // padding: 12,
    // shadowColor: "#000",
    // shadowOffset: {
    //   width: 0,
    //   height: 1,
    // },
    // shadowOpacity: 0.2,
    // shadowRadius: 1.41,

    // elevation: 2,
  },
  icon: {
    marginRight: 5,
  },
  item: {
    padding: 17,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  textItem: {
    flex: 1,
    fontSize: 16,
  },
  placeholderStyle: {
    fontSize: 16,
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
  uImg: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    position: "absolute",
    height: 300,
  },
  tycontainer: {
    flexDirection: "row",
  },

  vwtouch: {
    backgroundColor: "#f79b39",
    width: "100%",
    padding: 8,
    height: 180,
    //margin: 5,
    borderRadius: 6,
    borderColor: "blue",
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowOffset: {
      height: 4,
      width: 2,
    },
  },
  wtouch: {
    backgroundColor: "#FCDEBD",
    width: Platform.OS === "ios" ? "98%" : "99%",
    height: 120,
    margin: 3,
    borderRadius: 5,
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowOffset: {
      height: 5,
      width: 2,
    },
  },
  vtouch: {
    backgroundColor: "#FCDEBD",
    width: width,
    height: Platform.OS === "android" ? width : height / 2,
    margin: 3,
    borderRadius: 12,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
  },
  txti: {
    fontSize: 16,
    fontWeight: "bold",
    color: "white",
  },
  ic: {
    padding: 2,
    borderRadius: 7,
    width: 10,
    marginTop: 4,
  },
  smbtn: {
    height: 40,
    width: 90,
    marginTop: 14,
    marginLeft: 4,
    // marginBottom: 3,
    justifyContent: "flex-start",
    backgroundColor: "#4bdbed",
    borderRadius: 5,
    alignItems: "center",
    shadowOpacity: 0.3,
    shadowRadius: 3,
    shadowOffset: {
      height: 5,
      width: 2,
    },
  },
  btntxt1: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    //alignSelf: "center",
    margin: 8,
  },
  pritxt: {
    fontSize: 18,
    fontWeight: "normal",
    color: "white",
  },
  prtxt: {
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
  },
  currencynav: {
    padding: 3,
    fontSize: 20,
    color: "white",
  },
  profileIcon: {
    resizeMode: "contain",
    width: 90,
    height: 100,
    borderRadius: 50,
    alignSelf: "flex-end",
    marginTop: 35,
    marginLeft: 10,
    marginRight: 10,
  },
  iconStyle: {
    width: 15,
    height: 15,
    marginHorizontal: 5,
  },
  customItem: {
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
  },
});
